---
- name: Ubuntu 主机连接测试
  hosts: all
  gather_facts: false

  tasks:
    - name: 打印实际连接参数
      debug:
        msg: |
          正在连接主机: {{ ansible_host }}
          SSH端口: {{ ansible_port | default('22') }}
          用户: {{ ansible_user | default('root') }}

    - name: 使用 Ansible ping 测试连接
      ansible.builtin.ping:
